//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources
{
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource_nl
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource_nl()
        {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Resource_nl", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Bereken uw aanvullend pensioen en dubbel voordeel.
        /// </summary>
        internal static string breadcrumb
        {
            get
            {
                return ResourceManager.GetString("breadcrumb", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to &lt;a target=&quot;_blank&quot; href=&quot;https://www.ing.be/nl&quot;&gt;ing.be&lt;/a&gt;.
        /// </summary>
        internal static string footer_ing
        {
            get
            {
                return ResourceManager.GetString("footer_ing", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to &lt;a target=&quot;_blank&quot; href=&quot;http://www.ing.be/privacy&quot;&gt;Privacy&lt;/a&gt;.
        /// </summary>
        internal static string footer_privacy
        {
            get
            {
                return ResourceManager.GetString("footer_privacy", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;&amp;copy; {0} ING België nv, alle rechten voorbehouden&lt;/p&gt;.
        /// </summary>
        internal static string footer_rights
        {
            get
            {
                return ResourceManager.GetString("footer_rights", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to &lt;a target=&quot;_blank&quot; href=&quot;http://www.ing.be/veiligheid&quot;&gt;Veiligheid&lt;/a&gt;.
        /// </summary>
        internal static string footer_security
        {
            get
            {
                return ResourceManager.GetString("footer_security", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to &lt;span class=&quot;divider&quot;&gt; | &lt;/span&gt;.
        /// </summary>
        internal static string footer_sep
        {
            get
            {
                return ResourceManager.GetString("footer_sep", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to &lt;a target=&quot;_blank&quot; href=&quot;http://www.ing.be/legal&quot;&gt;Gebruiksvoorwaarden&lt;/a&gt;.
        /// </summary>
        internal static string footer_terms
        {
            get
            {
                return ResourceManager.GetString("footer_terms", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to U bent hier: .
        /// </summary>
        internal static string hier
        {
            get
            {
                return ResourceManager.GetString("hier", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string legal_prefix
        {
            get
            {
                return ResourceManager.GetString("legal_prefix", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Uw persoonsgegevens worden door ING België NV  verwerkt voor de  behandeling van de aanvraag van uw kennis en/of om hem/haar bankdiensten aan te bieden. &lt;br /&gt;U kan kennis nemen van de gegevens die op u betrekking hebben en deze laten verbeteren. Voor alle bijkomende informatie, gelieve onze Privacy Policy te consulteren..
        /// </summary>
        internal static string legal_text
        {
            get
            {
                return ResourceManager.GetString("legal_text", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Bescherming van de persoonlijke levenssfeer.
        /// </summary>
        internal static string legal_title
        {
            get
            {
                return ResourceManager.GetString("legal_title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Contest Template.
        /// </summary>
        internal static string meta_description
        {
            get
            {
                return ResourceManager.GetString("meta_description", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Contest Template.
        /// </summary>
        internal static string meta_keywords
        {
            get
            {
                return ResourceManager.GetString("meta_keywords", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Contest Template.
        /// </summary>
        internal static string meta_title
        {
            get
            {
                return ResourceManager.GetString("meta_title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to This is the second legal.
        /// </summary>
        internal static string shortcut_text
        {
            get
            {
                return ResourceManager.GetString("shortcut_text", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Legal 2.
        /// </summary>
        internal static string shortcut_title
        {
            get
            {
                return ResourceManager.GetString("shortcut_title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Contest Template.
        /// </summary>
        internal static string subTitle
        {
            get
            {
                return ResourceManager.GetString("subTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to ING | Contest template.
        /// </summary>
        internal static string title
        {
            get
            {
                return ResourceManager.GetString("title", resourceCulture);
            }
        }
    }
}
